import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Toaster from "@/components/UI/Toaster/Toaster";
import { SessionProvider } from "next-auth/react";
import { ClientSessionProvider } from "@/lib/providers/client-session-provider";
import { useEffect } from "react";
import { useFavoriteState } from "@/lib/store/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Магазин спортивного питания",
  description: "Generated by create next app"
};

type Params = {
  session: any;
  params: any;
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientSessionProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <script
            dangerouslySetInnerHTML={{
              __html: `
        try {
          if (localStorage.theme === "dark" || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark')
          } else {
            document.documentElement.classList.remove('dark')
          }
        } catch (_) {}
      `
            }}
          />
        </head>
        <body className={`bg-gray-14 dark:bg-gray-2 ${inter.className}`}>
          {/* <Toaster /> */}
          <div id="modals"></div>
          {children}
        </body>
      </html>
    </ClientSessionProvider>
  );
}
